//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculPartsHeritage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYANTDROIT
    {
        public int ADRID { get; set; }
        public Nullable<int> NOMENCLATUREID { get; set; }
        public int UTILISATEURID { get; set; }
        public string DESIGNATION { get; set; }
        public string IMAGEADR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public string TYPEHERITIER { get; set; }
    
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual HERITIER HERITIER { get; set; }
    }
}
