//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculPartsHeritage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN
    {
        public int BIENID { get; set; }
        public Nullable<int> HERITAGEID { get; set; }
        public string DESCRIPTION { get; set; }
        public string EVALUATEUR { get; set; }
        public string AFFECTATION { get; set; }
    
        public virtual HERITAGE HERITAGE { get; set; }
    }
}
