//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculPartsHeritage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class connection
    {
        public Nullable<int> idlogin { get; set; }
        public string email { get; set; }
        public string MotDePasse { get; set; }
    }
}
